### PR TITLE
Add WinGet Releaser

### LINKED ISSUE #2: Use WinGet Releaser to package to WinGet
Hi, I would suggest using [WinGet Releaser](https://bittu.eu.org/docs/wr-intro/) to submit future packages for this project to winget-pkgs.

It is a GitHub actions workflow that will run on every release, retrieve the installer from the GitHub release assets and automatically create a PR to winget-pkgs with the new update (from your account with a token). I saw that with 1.3.2 you tried to overwrite the previous version on winget-pkgs - I'm not sure whether this is intentional but WinGet Releaser will allow you to do this if you do only wish to have the latest version on winget-pkgs.

It would look like this:

```yml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: Xanthus58.ValorantRandomizer
          installers-regex: '\.exe$'
          delete-previous-version: 'true' # Optional
          token: ${{ secrets.WINGET_TOKEN }}
```

I'm happy to make a PR for this change to this repo :)

### PR DESCRIPTION
**Pull request by russellbanks**
This pull request adds a workflow that automatically publishes Valorant Randomizer to WinGet every release, as discussed in #2. *Please do not merge this pull request without reading the below and making the required changes* (The token part is the important bit) :)

- `runs-on: windows-latest`

The WinGet Releaser action can only run on Windows.

</br>

- `identifier: Xanthus58.ValorantRandomizer`

This is the identifier for Valorant Randomizer on Winget. It will use this to find ValorantRandomizer's current package on WinGet.

</br>

- `installers-regex: '\.exe$'`

This will make all `.exe` files in the assets of the latest Valorant Randomizer release to be included in the pull request (Only one exe must be present in the assets as that is what is currently on WinGet - if you ever wanted to provide more installers, a bit of manual intervention would be required).

</br>

- `delete-previous-version: 'true'`

This is optional, and you are welcome to change this to false (or omit it; the default is false). This will essentially overwrite the previous version on WinGet packages, so that only this new version is stored on WinGet.

</br>

- `token: ${{ secrets.WINGET_TOKEN }}`

This is the bit that will require action from yourself. This is a GitHub token with which the action will authenticate with GitHub and create a pull request on the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository.

To do this, you will need to:

1. Create a Personal Access Token (PAT) with `public_repo` scope on your GitHub account.
image

2. Create a repository secret containing the token. **Super important: call this token: `WINGET_TOKEN`**.
See [using encrypted secrets in a workflow](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for more details.

</br>

**Finally, make sure you have a fork of [winget-pkgs](https://github.com/microsoft/winget-pkgs) on your GitHub account. Please do not delete the fork after a pull request has been merged as the action will use that fork for making a branch and merging it with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every Valorant Randomizer release.**

The above is made on the assumption that the account that the token is from (and the fork is present) is @Xanthus58. If you would like this to be done by another account, the token would have to be from the different user and an extra line would have to be added: `fork-user: # Username of other user` (this defaults to the repository owner, which is why it doesn't have to be added)

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro) and the source code is [here](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/releaser-action/action.yml).

If you are interested in what a pull request made by this action looks like, here is one from my account: [#61982 on winget-pkgs](https://github.com/microsoft/winget-pkgs/pull/61469).

### CODE REVIEW

**Comment by zephiowl** [comment]
@russellbanks Hey I just wanted to say thank you; for informing me about the project; making the PR and helping out in general. I'll look into using this for some of my other projects as well.

**Comment by russellbanks** [comment]
No problem :)

**Comment by russellbanks** [comment]
Just to check - have you been able to add the token to this repo?

**Comment by zephiowl** [comment]
> Just to check - have you been able to add the token to this repo?

I got it all working I believe. Worst case I should be able to figure it out from the documentation you provided

**Pull request merged**
